[project]
name = "open-asr-leaderboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "datasets>=3.0.0",
    "evaluate",
    "huggingface-hub[hf-transfer]",
    "jiwer",
    "kaldialign",
    "librosa",
    "num2words",
    "regex",
    "torch",
    "torchcodec",
    "tqdm"
]

[project.scripts]
open-asr-leaderboard = "open_asr_leaderboard:main"

[dependency-groups]
nemo = [
    "cuda-python>=12.4",
    "IPython",
    "nemo_toolkit[asr]",
    "soundfile"
]

ctranslate2 = [
    "ctranslate2",
    "faster-whisper>=0.8.0",
    "transformers",
]

transformers = [
    "accelerate",
    "transformers>=4.45.0",
]
